name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install composer dependencies
        run: composer install

      - name: Execute tests
        run: phpunit
